name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ main ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.resultado }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuraci칩n
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest -v tests/test_logica.py
      - name: Validar resultado con errores
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Una o varias pruebas fallaron
        run: echo "::set-output name=resultado::$MENSAJE_ERROR"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        env:
          MENSAJE_EXITO: Todas las pruebas pasaron
        run: echo "::set-output name=resultado::$MENSAJE_EXITO"
      - name: C치lculo cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest -v tests/test_logica.py
          coverage report -m
  automerge:
    name: Automerge
    needs: job1
    runs-on: ubuntu-latest
    steps:

      - name: Automerge fallido
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Fall칩 el merge autom치tico

      - name: Automerge completo
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""