name: Releases
on:
  push:
    branches:
      - 'feature/HU**'
jobs:
  jobValidacion:
    name: Palabra clave
    runs-on: ubuntu-latest
    steps:
      - name: Validacion Release
        if: ${{ !contains(github.event.head_commit.message, 'RELEASE') }}
        run: |
            echo "No se puede hacer release sin la solicitud de RELEASE en el commit"
            exit 1
        env:
          RAMA_FEATURE: ${{ github.ref }}

  jobPruebas:
    name: Pruebas
    runs-on: ubuntu-latest
    needs: jobValidacion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuración
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest -v tests/test_logica.py

